version: "3"
services:

  app:
    build: .
    command: bin/rails server -b 0.0.0.0 -p 3000
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    links:
      - db
      - redis
    ports:
      - 3000:3000

  db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:alpine
