default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: app
  password: password

development:
  <<: *default
  database: battlesnake_development

test:
  <<: *default
  database: battlesnake_test

production:
  <<: *default
  database: battlesnake_production
